---
title: "QRM2"
author: "Groepje 47"
date: "2026-09-04"
output: html_document
---
1 Week 1
1. Find the dataset “movies5.tsv” on Canvas. Describe your data set: How many observations does it
have. How many variables are there? How many subjects? What consists of a subject? [4 points]
#WRITE YOUR CODE HERE
Your Answer:
Write your response here.
2. Which of the following types of variables are present in your data set? (i) nominal; (ii) ordinal; (iii);
interval; (iv) ratio. If present, name one example of such a variable present in your data set. [4 points]
#WRITE YOUR CODE HERE
Your Answer:
Write your response here.
3. A movie studio wants to know which types of movies give maximal profit. Perform the following steps
to provide the movie studio with an analysis which corresponds to their request:
a. Create the variable profits as the revenue of a movie minus its budget. Report its mean, median,
maximum, and minimum. [2 points]
b. Which movie has the highest profits in your data set and how much are these profits. Which movie
has the lowest and how much are its profits? If multiple movies have the exact same highest or lowest
profits, give only one example. [2 points]
c. Create a boxplot of the variable profits. Make sure it has an appropriate title, and appropriate titles
and labels for the x- and y-axis. Give Q1, Q2, Q3, and Q4. What does this tell you about the nature of
making money in the movies industry? [2 points]
d. Add a new variable to your data set the log of profits. When creating this variable, what happens to
movies for which profits is zero or negative? What then happens when you calculate the mean of log of
profits? [2 points]
e. For movies that have a profit of zero or less, replace log of profits with “NA”. What is now the mean of
log of profits? Create a boxplot for log of profits, again with an appropriate title, x- and y-axis labels.
How does it compare to the boxplot you made under c.)? [2 points]
f. Create a scatterplot of with the runtime of movies on the x-axis and the average vote of movies on the
y-axis. What do you conclude from the scatterplot? Are movies with a longer runtime considered worse
or better by the audience, or does the audience not have a preference? Why do you think this is the
case? [2 points]
For each step, you should provide first all the code you used to answer the question and then formulate an
answer using full sentences.
2
Step a
#WRITE YOUR CODE HERE
Your Answer:
Write your formulated response here.
Step b
#WRITE YOUR CODE HERE
Your Answer:
Write your formulated response here.
Step c
#WRITE YOUR CODE HERE
Your Answer:
Write your formulated response here.
Step d
#WRITE YOUR CODE HERE
Your Answer:
Write your formulated response here.
Step e
#WRITE YOUR CODE HERE
Your Answer:
Write your formulated response here.
Step f
#WRITE YOUR CODE HERE
Your Answer:
Write your formulated response here.
